# Generated by Django 5.2.7 on 2026-09-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True)),
                ('attachment_id', models.CharField(max_length=255)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('file_size', models.IntegerField(default=0)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('min_confidence', models.FloatField(db_index=True, default=0.0)),
                ('oe_code', models.CharField(blank=True, max_length=50)),
                ('oe_confidence', models.FloatField(default=0.0)),
                ('oe_matched', models.BooleanField(default=False)),
                ('oe_candidates', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('NOT_AN_ORDER', 'Not an order'), ('NEEDS_REVIEW', 'Needs review'), ('AUTO_APPROVED', 'Auto approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='NEW', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('message_id', 'attachment_id')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(default='system', max_length=150)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='optic_bot.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
