# Generated by Django 5.2.7 on 2026-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='export_s3_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
