# Generated by Django 5.2.7 on 2026-09-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic_bot', '0002_order_export_s3_key_order_exported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oe_match_reason',
            field=models.TextField(blank=True),
        ),
    ]
