# Generated by Django 5.2.7 on 2026-09-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic_bot', '0003_order_oe_match_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oe_uom',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
