# Generated by Django 5.2.7 on 2026-09-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic_bot', '0004_order_oe_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('NOT_AN_ORDER', 'Not an order'), ('NEEDS_REVIEW', 'Needs review'), ('AUTO_APPROVED', 'Auto approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='NEW', max_length=20),
        ),
    ]
