# Generated by Django 5.2.7 on 2026-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic_bot', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('stuck_since', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
