# Generated by Django 5.2.7 on 2026-09-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic_bot', '0006_mailwatermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailwatermark',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailwatermark',
            name='sweep_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
